[package]
name = "neovim-sys"
version = "0.1.0"
authors = ["Steve Loveless <steve.loveless@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]

[build-dependencies]
bindgen = "0.59.1"
