name: Testing

on: [push]

jobs:
  test-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as it uses the current rustc version as its cache key
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Run Rust tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --workspace

  test-miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as it uses the current rustc version as its cache key
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: miri

      - uses: Swatinem/rust-cache@v1

      - name: Run miri test
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: miri
          args: test --all-features --workspace
